---
- import_tasks: "uninstall-docker.yml"
- import_tasks: "install-docker.yml"

- name: "Add vagrant user to docker group io order to use '/var/run/docker.sock'"
  user:
    name: "vagrant"
    group: "docker"
...